### ISSUE TITLE
Be more explicit about architectures

### ISSUE THREAD

**Issue by toastal** [purerl/nixpkgs-purerl#9]
Looking at your build outputs, it seems only x86_64 architectures are built by CI. I would suggest being more explicit rather than assuming anything that isn't on the Darwin kernel (which is presupposing Rosetta 2 will kick in and be fully compatible on the newer ARM-based Macs) is x86_64 Linux. This would help give meaningful errors to folks on less popular devices and how they will need to build from source.

I merged a version for 0.15.3 into the `easy-purescript-nix` repository like this to cover the arch issue: https://github.com/justinwoo/easy-purescript-nix/blob/master/purs/0.15.3.nix

**Comment by nwolverson** [comment]
I know there was a back and forth on that change related to M1 - @srstrong did that get to a point everyone was happy with? Presumably we can do the same here

**Comment by nwolverson** [comment]
Think this is now resolved, with arm assets & similar arch check
